name: FTP Upload

on:
  push:
    branches:
      - main  # Solo en la rama main

jobs:
  upload:
    name: Upload to FTP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload files via FTP
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          server: ${{ secrets.FTP_SERVER }}  #  configurar este secreto en la configuración del repositorio
          username: ${{ secrets.FTP_USERNAME }}  #  configurar este secreto en la configuración del repositorio
          password: ${{ secrets.FTP_PASSWORD }}  #  configurar este secreto en la configuración del repositorio
          local-dir: .  
          remote-dir: /public_html/  # Ruta en el servidor FTP 
